name: "opensyd_dart"
author: Sergio Lisan <sels@venosyd.com>
publish_to: "none"

version: 3.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  crypto:
  http:
  intl:
  meta:
  universal_html:
  verbal_expressions:
    # git:
    #   url: git@github.com:sergioelisan/DartVerbalExpressions.git
    #   ref: 0.5.0-nullsafety
    